//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTunesMatchTagger {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>US</string>\r\n  <string>GB</string>\r\n  <string>AU</string>\r\n  <string>FR</s" +
            "tring>\r\n  <string>DE</string>\r\n  <string>CA</string>\r\n  <string>IT</string>\r\n  <" +
            "string>JP</string>\r\n  <string>DZ</string>\r\n  <string>AO</string>\r\n  <string>AI</" +
            "string>\r\n  <string>AG</string>\r\n  <string>AR</string>\r\n  <string>AM</string>\r\n  " +
            "<string>AT</string>\r\n  <string>AZ</string>\r\n  <string>BS</string>\r\n  <string>BH<" +
            "/string>\r\n  <string>BD</string>\r\n  <string>BB</string>\r\n  <string>BY</string>\r\n " +
            " <string>BE</string>\r\n  <string>BZ</string>\r\n  <string>BM</string>\r\n  <string>BO" +
            "</string>\r\n  <string>BW</string>\r\n  <string>BR</string>\r\n  <string>BN</string>\r\n" +
            "  <string>BG</string>\r\n  <string>CM</string>\r\n  <string>KY</string>\r\n  <string>C" +
            "L</string>\r\n  <string>CN</string>\r\n  <string>CO</string>\r\n  <string>CR</string>\r" +
            "\n  <string>CI</string>\r\n  <string>HR</string>\r\n  <string>CY</string>\r\n  <string>" +
            "CZ</string>\r\n  <string>DK</string>\r\n  <string>DM</string>\r\n  <string>DO</string>" +
            "\r\n  <string>EC</string>\r\n  <string>EG</string>\r\n  <string>SV</string>\r\n  <string" +
            ">EE</string>\r\n  <string>ET</string>\r\n  <string>FI</string>\r\n  <string>GH</string" +
            ">\r\n  <string>GR</string>\r\n  <string>GD</string>\r\n  <string>GT</string>\r\n  <strin" +
            "g>GY</string>\r\n  <string>HN</string>\r\n  <string>HK</string>\r\n  <string>HU</strin" +
            "g>\r\n  <string>IS</string>\r\n  <string>IN</string>\r\n  <string>ID</string>\r\n  <stri" +
            "ng>IE</string>\r\n  <string>IL</string>\r\n  <string>JM</string>\r\n  <string>JO</stri" +
            "ng>\r\n  <string>KZ</string>\r\n  <string>KE</string>\r\n  <string>KR</string>\r\n  <str" +
            "ing>KW</string>\r\n  <string>LV</string>\r\n  <string>LB</string>\r\n  <string>LY</str" +
            "ing>\r\n  <string>LI</string>\r\n  <string>LT</string>\r\n  <string>LU</string>\r\n  <st" +
            "ring>MO</string>\r\n  <string>MK</string>\r\n  <string>MG</string>\r\n  <string>MY</st" +
            "ring>\r\n  <string>MV</string>\r\n  <string>ML</string>\r\n  <string>MT</string>\r\n  <s" +
            "tring>MU</string>\r\n  <string>MX</string>\r\n  <string>MD</string>\r\n  <string>MS</s" +
            "tring>\r\n  <string>MM</string>\r\n  <string>NP</string>\r\n  <string>NL</string>\r\n  <" +
            "string>NZ</string>\r\n  <string>NI</string>\r\n  <string>NE</string>\r\n  <string>NG</" +
            "string>\r\n  <string>NO</string>\r\n  <string>OM</string>\r\n  <string>PK</string>\r\n  " +
            "<string>PA</string>\r\n  <string>PY</string>\r\n  <string>PE</string>\r\n  <string>PH<" +
            "/string>\r\n  <string>PL</string>\r\n  <string>PT</string>\r\n  <string>QA</string>\r\n " +
            " <string>RO</string>\r\n  <string>RU</string>\r\n  <string>KN</string>\r\n  <string>LC" +
            "</string>\r\n  <string>VC</string>\r\n  <string>SA</string>\r\n  <string>SN</string>\r\n" +
            "  <string>RS</string>\r\n  <string>SG</string>\r\n  <string>SK</string>\r\n  <string>S" +
            "I</string>\r\n  <string>ZA</string>\r\n  <string>ES</string>\r\n  <string>LK</string>\r" +
            "\n  <string>SR</string>\r\n  <string>SE</string>\r\n  <string>CH</string>\r\n  <string>" +
            "TW</string>\r\n  <string>TZ</string>\r\n  <string>TH</string>\r\n  <string>TT</string>" +
            "\r\n  <string>TN</string>\r\n  <string>TR</string>\r\n  <string>TC</string>\r\n  <string" +
            ">UG</string>\r\n  <string>UA</string>\r\n  <string>AE</string>\r\n  <string>UY</string" +
            ">\r\n  <string>UZ</string>\r\n  <string>VE</string>\r\n  <string>VN</string>\r\n  <strin" +
            "g>VG</string>\r\n  <string>YE</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StoreCountries {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StoreCountries"]));
            }
            set {
                this["StoreCountries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Usklađena AAC audio datoteka</string>
  <string>Egyező AAC-hangfájl</string>
  <string>File audio AAC corrispondente</string>
  <string>マッチした AAC オーディオファイル</string>
  <string>AAC-Audiodatei (passend)</string>
  <string>Αντιστοιχισμένο αρχείο ήχου AAC</string>
  <string>Matched AAC audio file</string>
  <string>Archivo de audio AAC coincidente</string>
  <string>Täsmäävä AAC-äänitiedosto</string>
  <string>Fichier audio AAC mis en correspondance</string>
  <string>Fitxer d’àudio AAC aparellat</string>
  <string>Nahrazený soubor AAC audio</string>
  <string>Matchet AAC-lydfil</string>
  <string>Matched AAC audio file</string>
  <string>Eşleştirilen AAC ses dosyası</string>
  <string>Зіставлений аудіофайл AAC</string>
  <string>匹配的 AAC 音频文件</string>
  <string>比對成功的 AAC 音訊檔</string>
  <string>Найдено совпадение аудиофайла AAC</string>
  <string>Zhodný AAC audiosúbor</string>
  <string>Matchad AAC-ljudfil</string>
  <string>ไฟล์เสียง AAC ที่ตรงกัน</string>
  <string>Gematcht AAC-audiobestand</string>
  <string>dopasowany plik audio AAC</string>
  <string>Arq. áudio AAC dispon.</string>
  <string>Ficheiro de áudio AAC do iTunes Match</string>
  <string>fișier audio AAC corelat</string>
  <string>일치하는 AAC 오디오 파일</string>
  <string>Matchet AAC-lydfil</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MatchedKindAsString {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MatchedKindAsString"]));
            }
            set {
                this["MatchedKindAsString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://code.google.com/p/itunes-match-tagger")]
        public string ProjectUrl {
            get {
                return ((string)(this["ProjectUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("schirkan@googlemail.com")]
        public string AuthorEmail {
            get {
                return ((string)(this["AuthorEmail"]));
            }
        }
    }
}
